version: '3'

services:
  api-gympass-pg:
    image: bitnami/postgresql
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_DATABASE=apigympass
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker